<?xml version="1.0"?>
<!DOCTYPE CATALOG [
        <!ELEMENT CATALOG (PRODUCT+)>
        <!ELEMENT PRODUCT
                (SPECIFICATIONS+,OPTIONS?,PRICE+,NOTES?)>
        <!ATTLIST PRODUCT
                NAME CDATA #IMPLIED
                CATEGORY (HandTool|Table|Shop-Professional) "HandTool"
                PARTNUM CDATA #IMPLIED
                PLANT (Pittsburgh|Milwaukee|Chicago) "Chicago"
                INVENTORY (InStock|Backordered|Discontinued) "InStock">
        <!ELEMENT SPECIFICATIONS (#PCDATA)>
        <!ATTLIST SPECIFICATIONS
                WEIGHT CDATA #IMPLIED
                POWER CDATA #IMPLIED>
        <!ELEMENT OPTIONS (#PCDATA)>
        <!ATTLIST OPTIONS
                FINISH (Metal|Polished|Matte) "Matte"
                ADAPTER (Included|Optional|NotApplicable) "Included"
                CASE (HardShell|Soft|NotApplicable) "HardShell">
        <!ELEMENT PRICE (#PCDATA)>
        <!ATTLIST PRICE
                MSRP CDATA #IMPLIED
                WHOLESALE CDATA #IMPLIED
                STREET CDATA #IMPLIED
                SHIPPING CDATA #IMPLIED>
        <!ELEMENT NOTES (#PCDATA)>
        ]>
<CATALOG>
    <PRODUCT NAME="SwedeTable" CATEGORY="Table" PARTNUM="1" PLANT="Milwaukee" INVENTORY="Discontinued" >
        <SPECIFICATIONS WEIGHT="200">
            Living room table
        </SPECIFICATIONS>
        <OPTIONS FINISH="Metal" ADAPTER="NotApplicable" CASE="NotApplicable">Amarillo o Azul</OPTIONS>
        <PRICE MSRP="1" SHIPPING="3" STREET="Colorado" WHOLESALE="Yes">400</PRICE>
        <NOTES>Marca Ikea</NOTES>
    </PRODUCT>
    <PRODUCT NAME="Alicates" PARTNUM="2">
        <SPECIFICATIONS>
            30cm
        </SPECIFICATIONS>
        <PRICE SHIPPING="3" WHOLESALE="Yes">2</PRICE>
        <NOTES>Marca Phillips</NOTES>
    </PRODUCT>
</CATALOG>